### PR TITLE
Port rviz and launch files to ROS2

### PR DESCRIPTION
**Pull request by rotu**

### CODE REVIEW

**Comment by allenh1** [comment]
@rotu thanks for the patch! Would appreciate it if you could refrain from the white space changes in the CMakeLists.txt file, but, otherwise, I'm fine to merge this on in.

**Review by allenh1 — CHANGES_REQUESTED** [review]
See note above

**Comment by rotu** [comment]
> @rotu thanks for the patch! Would appreciate it if you could refrain from the white space changes in the CMakeLists.txt file, but, otherwise, I'm fine to merge this on in.

Oops! I blame JetBrains and their default settings :-p

**Comment by allenh1** [comment]
> Oops! I blame JetBrains and their default settings

Haha, no worries. Got just a few more left to fix (indentation changes).

**Comment by rotu** [comment]
> > Oops! I blame JetBrains and their default settings
> 
> Haha, no worries. Got just a few more left to fix (indentation changes).

It's a wonder I remember to put on pants most days

**Review by allenh1 — APPROVED** [review]

**Comment by allenh1** [comment]
@rotu thanks very much! I'm actually re-implementing the driver using ROS 2 paradigms (on a different branch), so the whitespace change removal helps reduce merge conflicts. Thanks for iterating. :)

**Pull request merged**
