### PR TITLE
Use Composition Nodes in Luanch Files

### PR DESCRIPTION
**Pull request by allenh1**
Updates launch files to use composition nodes, as implemented in #3.

Signed-off-by: Hunter L. Allen <hallen@kns.com>

@rotu FYI

### CODE REVIEW

**Comment by rotu** [comment]
Thanks!

**Comment by rotu** [comment]
I think you have some cleanup to do. Did you mean to have a rplidar_node.cpp *and* a node.cpp?
Also, standalone_rplidar.cpp and standalone_prlidar.cpp?

**Comment by allenh1** [comment]
> Did you mean to have a rplidar_node.cpp and a node.cpp?

Yes. I don't want to remove the original driver, because I will choose to rebase on top of the upstream repo every so often & this would not be possible with the `rplidar_node.cpp` version (which will just be out of date when I do that, I think). The point here was to re-port the driver with composition for a demo I was doing.

> Also, standalone_rplidar.cpp and standalone_prlidar.cpp?

That was a typo, and I will clean that up in a PR at some point (you're more than welcome to remove it if you have a few).

**Comment by rotu** [comment]
So what's the intended use of node versus rplidar_node? I had a fix to node that I wanted to push to you but then I realized that because of the duplication, I'd have to fix the same bug in both places instead of just the one.

**Comment by allenh1** [comment]
> So what's the intended use of node versus rplidar_node?

I'd like to keep the direct port from upstream around in case they make changes there so that rebasing will pull in there changes, and I can move those changes into the composable version when needed. It doesn't really hurt to have the original around, since it's the official one.

> I had a fix to node that I wanted to push to you but then I realized that because of the duplication, I'd have to fix the same bug in both places instead of just the one.

Depending on what the fix is, it would probably be best to push that change to the ROS 1 repository, and then I'll pull it here. That way you don't have to make multiple changes. If there's something ROS 2 specific, I'd appreciate it if you would file an issue so that this thread can be standalone.

**Pull request merged**
